### ISSUE TITLE
Does not detect resolutions higher than 1920 x 1080

### ISSUE THREAD

**Issue by R0B0LUT10N** [marzer/RSTK#1]
![rocksmith_toolkit_resolution_limitation](https://user-images.githubusercontent.com/39630487/40556913-e745ac30-603d-11e8-81de-4d706b4e7502.png)

My native 2560x1600 is undetected.

**Comment by marzer** [comment]
Thanks for the report. The reason it's not being detected is that RSTK doesn't actually do any resolution detection at all; I merely spit out a list of pre-defined resolutions based on what was in my game's resolutions menu. Lazy, I know. Enumerating the actual resolutions supported by the system isn't overly hard so I can add support for that.

In reading the code again just now I've also spotted a few other issues that need fixing, so I'll do those as well.

**Comment by marzer** [comment]
@R0B0LUT10N I pushed [a new release](https://github.com/marzer/RSTK/releases/tag/v1.4) containing this fix. I haven't had time to test it thoroughly so please let me know if there's any bugs or strange behavior.
